# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - dev-sontiravi-appservice

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'dev-sontiravi-appservice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c45e152b827b4d5ea783c9b684367d41 }}
        package: '${{ github.workspace }}/target/*.war'